---
# task/configure file for hashicorp_consul
- name: "Copy consul.hcl template"
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: "{{ hashi_consul_config_dir }}/consul.hcl"
    owner: "{{ hashi_consul_user }}"
    group: "{{ hashi_consul_group }}"
    mode: '0600'
  notify:
    - "systemctl-enable-consul"
    - "systemctl-restart-consul"

- name: "Create empty consul.env"
  ansible.builtin.file:
    path: "{{ hashi_consul_config_dir }}/consul.env"
    owner: "{{ hashi_consul_user }}"
    group: "{{ hashi_consul_group }}"
    mode: '0600'
    state: file
