---
# task/main file for hashicorp_consul
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml
  when: hashi_consul_install

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml
