---
# task/prerequisites file for hashicorp_consul
- name: "Create group consul"
  ansible.builtin.group:
    name: consul
    state: present

- name: "Create user consul"
  ansible.builtin.user:
    name: consul
    group: consul
    shell: /bin/false
    state: present

- name: "Create directory /etc/consul.d"
  ansible.builtin.file:
    path: "/etc/consul.d"
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: "Create directory {{ hashi_consul_data_dir }}"
  ansible.builtin.file:
    path: "{{ hashi_consul_data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: '0755'
