---
name: build
on: [push]

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls ${{ gitea.workspace }}