---
# handlers file for hashicorp_consul
- name: "Enable consul service"
  ansible.builtin.service:
    name: consul
    enabled: true
  listen: "systemctl-enable-consul"
  notify: "systemctl-restart-consul"

- name: "Start consul service"
  ansible.builtin.service:
    name: consul
    state: restarted
  listen: "systemctl-restart-consul"
  when: hashi_consul_start_service
