---
# handlers file for hashicorp_consul
- name: "Enable consul service"
  ansible.builtin.service:
    name: consul
    enabled: true
  listen: "systemctl-enable-consul"
  notify: "want-started"

- name: "Check if consul needs to be started"
  ansible.builtin.assert:
    that: hashi_consul_start_service
    quiet: true
  changed_when: true
  listen: "want-started"
  notify: "systemctl-restart-consul"

- name: "Start consul service"
  ansible.builtin.service:
    name: consul
    state: restarted
  listen: "systemctl-restart-consul"
